gems:
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: APlaybookOrg

permalink: /:categories/:title.html

name: Analytics Playbook
description: An Open Source Repository for Analytical Techniques.
url: http://analyticsplaybook.org